export interface Sales {

  orderNumber:number,
  orderDate:string,
  requiredDate:string,
  shippedDate:string,
  status:string,
  comments:string,
  customerNumber:string,
  productCode:String,
  quantityOrdered:number,
  priceEach:number,
  orderLineNumber:number,
  productName:string,
  productLine:string,
  productVendor:string,
  productDescription:string,
  quantityInStock:number,
  buyPrice:number,
  MSRP:number,
}
